import JSZip from "jszip";
import { afterEach, describe, expect, it } from "vitest";

import { exportProjectBundle, importProjectBundle } from "@/core/project_bundle";
import { runProjectIntake } from "@/core/project_intake";
import { openProjectDb } from "@/db/dexie";
import { libraryDb } from "@/db/library";
import { createProject, deleteProject } from "@/db/repo/projects";

const CONTAINER_XML = `<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`;

const OPF = `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="bookid">urn:test:book</dc:identifier>
    <dc:title>Bundle Test</dc:title>
    <dc:language>en</dc:language>
  </metadata>
  <manifest>
    <item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine>
    <itemref idref="ch1"/>
  </spine>
</package>`;

const CH1 = `<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head><title>One</title></head>
  <body>
    <p>Hello world.</p>
  </body>
</html>`;

async function makeTestEpub(): Promise<ArrayBuffer> {
  const zip = new JSZip();
  zip.file("mimetype", "application/epub+zip", { compression: "STORE" });
  zip.file("META-INF/container.xml", CONTAINER_XML);
  zip.file("OEBPS/content.opf", OPF);
  zip.file("OEBPS/ch1.xhtml", CH1);
  const u8 = await zip.generateAsync({ type: "uint8array" });
  const buf = new ArrayBuffer(u8.byteLength);
  new Uint8Array(buf).set(u8);
  return buf;
}

async function blobToUint8(blob: Blob): Promise<Uint8Array> {
  return new Promise<Uint8Array>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () =>
      resolve(new Uint8Array(reader.result as ArrayBuffer));
    reader.onerror = () => reject(reader.error);
    reader.readAsArrayBuffer(blob);
  });
}

describe("exportProjectBundle", () => {
  const cleanup: string[] = [];

  afterEach(async () => {
    while (cleanup.length > 0) {
      const id = cleanup.pop()!;
      try {
        await deleteProject(id);
      } catch {
        // ignored — the test may have already deleted it
      }
    }
  });

  it("packs a manifest, project row, jsonl streams, and the original ePub", async () => {
    const bytes = await makeTestEpub();
    const project = await createProject({
      name: "Bundle Test",
      source_lang: "en",
      target_lang: "pt",
      source_filename: "bundle.epub",
      source_bytes: bytes,
    });
    cleanup.push(project.id);
    await runProjectIntake({
      project_id: project.id,
      source_lang: project.source_lang,
      target_lang: project.target_lang,
      epub_bytes: bytes,
      source_filename: "bundle.epub",
    });

    const { blob, filename } = await exportProjectBundle(project.id);
    expect(filename).toBe("Bundle_Test.epublate-project.zip");
    expect(blob).toBeInstanceOf(Blob);

    // jsdom's Blob#arrayBuffer is missing, so reach inside via the
    // generated bytes instead.
    const bundle_bytes = await blobToUint8(blob);
    const zip = await JSZip.loadAsync(bundle_bytes);
    const expected_files = [
      "manifest.json",
      "project.json",
      "library_row.json",
      "original.epub",
      "chapters.jsonl",
      "segments.jsonl",
      "glossary.jsonl",
      "events.jsonl",
    ];
    for (const file of expected_files) {
      expect(zip.file(file)).toBeTruthy();
    }
    const manifest = JSON.parse(
      await zip.file("manifest.json")!.async("string"),
    );
    expect(manifest.app).toBe("epublate-js");
    expect(manifest.project_id).toBe(project.id);

    // segments.jsonl should have at least one row (one per paragraph
    // in the test ePub).
    const segs = (await zip.file("segments.jsonl")!.async("string"))
      .split("\n")
      .filter(Boolean);
    expect(segs.length).toBeGreaterThan(0);
  });

  it("can re-import a bundle into a fresh project with a new id", async () => {
    const bytes = await makeTestEpub();
    const project = await createProject({
      name: "Roundtrip",
      source_lang: "en",
      target_lang: "pt",
      source_filename: "rt.epub",
      source_bytes: bytes,
    });
    cleanup.push(project.id);
    await runProjectIntake({
      project_id: project.id,
      source_lang: project.source_lang,
      target_lang: project.target_lang,
      epub_bytes: bytes,
      source_filename: "rt.epub",
    });
    const before_segments = await openProjectDb(project.id)
      .segments.toArray();

    const { blob } = await exportProjectBundle(project.id);
    const bundle_bytes = await blobToUint8(blob);
    // Copy into a stand-alone ArrayBuffer so the call is portable
    // across runtimes — `Uint8Array.buffer` may be a `SharedArrayBuffer`
    // depending on the FileReader implementation.
    const standalone = new ArrayBuffer(bundle_bytes.byteLength);
    new Uint8Array(standalone).set(bundle_bytes);
    const { project_id: new_id } = await importProjectBundle(standalone, {
      name_override: "Roundtrip (imported)",
    });
    cleanup.push(new_id);
    expect(new_id).not.toBe(project.id);

    const lib = await libraryDb().projects.get(new_id);
    expect(lib).toBeTruthy();
    expect(lib?.name).toBe("Roundtrip (imported)");

    const after_segments = await openProjectDb(new_id).segments.toArray();
    expect(after_segments).toHaveLength(before_segments.length);

    const project_row = await openProjectDb(new_id).projects.get(new_id);
    expect(project_row).toBeTruthy();
    expect(project_row?.id).toBe(new_id);
    expect(project_row?.source_lang).toBe("en");
    expect(project_row?.target_lang).toBe("pt");
  });
});
